### ISSUE TITLE
Do you have an evaluation plan for the GPT4o?

### ISSUE THREAD

**Issue by liguopeng0923** [zeyofu/BLINK_Benchmark#5]
I find that the GPT4o has a powerful ability for your bad cases.

**Comment by zeyofu** [comment]
Thanks! We'll update the GPT-4o and GPT-4 Turbo performances soon.

**Comment by RunsenXu** [comment]
Hi, thanks for your interesting work. I think it's a great contribution to the filed.

Do you consider testing the latest gpt-4o: GPT4o_20240806 and Claude3-5V_Sonnet?

**Comment by zeyofu** [comment]
Thanks for your interest and Great Point! We'll add them soon!

**Comment by RunsenXu** [comment]
I ran it myself. :) And for reference:

GPT4o_20240806: 57.92% 
Claude-3.5-sonnet: 58.39%

I use VLMEvalkit with the prompt: "<image>" * n + f"{prompt}" + BLINK_ADDITIONAL_PROMPT 

BLINK_ADDITIONAL_PROMPT = "Briefly explain your reasoning and finally give your answer with one alphabet in uppercase selected from the choices provided and enclose it within `` so that I can directly extract your answer."

They can follow instruction and no need GPT-postprocessing.

**Comment by zeyofu** [comment]
Thanks a lot for letting us know! Smart prompting on the answer extraction. I'll report the number on our page soon :D
